export interface NewsArticle {
  id: number;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  author: string;
  publishedAt: string;
  readTime: string;
  image: string;
  views: string;
  comments: number;
  tags: string[];
  trending?: boolean;
  featured?: boolean;
  modelResult?: 'Real' | 'AI-generated' | 'Fake' | 'Suspicious' | 'Unverified';
}

export const newsArticles: NewsArticle[] = [
  // Breaking News (13 articles)
  {
    id: 1,
    title: 'Kathmandu-Pokhara Railway Project Passes Testing Phase Successfully',
    excerpt: 'Nepal-India joint railway project successfully completes testing on Kathmandu-Pokhara corridor.',
    content: '<p>The Kathmandu-Pokhara railway corridor project has successfully completed its testing phase. This project is expected to revolutionize transportation between the two major cities and boost Nepal\'s economic development significantly.</p>',
    category: 'Breaking News',
    author: 'Rajiv Sharma',
    publishedAt: '5 minutes ago',
    readTime: '3 min',
    image: 'https://images.pexels.com/photos/2528118/pexels-photo-2528118.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '45.2k',
    comments: 234,
    tags: ['railway', 'infrastructure', 'technology'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 2,
    title: 'Lalitpur Smart City Construction Reaches 55% Completion',
    excerpt: 'Major smart city development project in Lalitpur achieves significant construction milestone.',
    content: '<p>The Lalitpur Brilliant City project has reached 55% completion with ongoing construction work accelerating. This ambitious smart city initiative is expected to transform urban living in the Kathmandu Valley region.</p>',
    category: 'Breaking News',
    author: 'Priya Bharti',
    publishedAt: '15 minutes ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3845682/pexels-photo-3845682.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '32.1k',
    comments: 156,
    tags: ['urban development', 'smart city', 'construction'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 3,
    title: 'Nepal Stock Exchange Records 40% Growth in Annual Trading',
    excerpt: 'Record foreign investment flows into Nepal Stock Exchange with 40% year-over-year growth.',
    content: '<p>The Nepal Stock Exchange has reported unprecedented 40% growth in trading volumes this year, driven by increased foreign investor participation. Market analysts predict continued growth as investor confidence strengthens.</p>',
    category: 'Breaking News',
    author: 'Amar Patel',
    publishedAt: '25 minutes ago',
    readTime: '3 min',
    image: 'https://images.pexels.com/photos/159888/pexels-photo-159888.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '28.5k',
    comments: 89,
    tags: ['economy', 'stocks', 'investment'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 4,
    title: 'Prime Minister Inaugurates 150 km Road Project in Panchthar',
    excerpt: 'Major road infrastructure project linking rural districts officially launched in eastern Nepal.',
    content: '<p>The Prime Minister inaugurated a 150-kilometer road construction project in Panchthar district. This critical infrastructure development will enhance connectivity for remote communities in eastern Nepal.</p>',
    category: 'Breaking News',
    author: 'Suresh Gupta',
    publishedAt: '35 minutes ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3184305/pexels-photo-3184305.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '21.3k',
    comments: 112,
    tags: ['infrastructure', 'development', 'government'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 5,
    title: 'Earthquake Preparedness Drill Held Across Kathmandu Valley',
    excerpt: 'Government conducts massive earthquake disaster response exercise involving multiple agencies.',
    content: '<p>Thousands of staff from various government departments participated in a large-scale earthquake preparedness drill across Kathmandu Valley. The exercise tested response protocols and coordination mechanisms for disaster management.</p>',
    category: 'Breaking News',
    author: 'Ram Kumar Singh',
    publishedAt: '45 minutes ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '18.9k',
    comments: 95,
    tags: ['disaster', 'earthquake', 'preparedness'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 6,
    title: 'Nepal Welcomes First International Climate Summit',
    excerpt: 'Environmental leaders from 50+ nations gather in Kathmandu for climate change conference.',
    content: '<p>Nepal successfully hosted its first international climate summit with representatives from over 50 countries. The conference focused on implementing renewable energy solutions and addressing climate change in South Asia.</p>',
    category: 'Breaking News',
    author: 'Meera Thapa',
    publishedAt: '1 hour ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3184427/pexels-photo-3184427.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '35.6k',
    comments: 201,
    tags: ['environment', 'climate', 'conference'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 7,
    title: 'New Airport Terminal Opens in Pokhara',
    excerpt: 'Expanded airport terminal facility now operational serving regional international flights.',
    content: '<p>The newly constructed terminal at Pokhara Airport officially opened, doubling the airport\'s passenger capacity. The modern facility includes enhanced security features and international standard amenities.</p>',
    category: 'Breaking News',
    author: 'Vikram Poudel',
    publishedAt: '1 hour ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3803517/pexels-photo-3803517.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '16.7k',
    comments: 78,
    tags: ['airport', 'infrastructure', 'tourism'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 8,
    title: 'COVID-19 Vaccination Campaign Reaches 80% Coverage',
    excerpt: 'Health authorities announce successful mass immunization achieving 80% population coverage.',
    content: '<p>Nepal\'s health ministry announced that the nationwide COVID-19 vaccination campaign has reached 80% population coverage. The achievement represents significant progress in public health infrastructure and awareness.</p>',
    category: 'Breaking News',
    author: 'Dr. Anita Sharma',
    publishedAt: '2 hours ago',
    readTime: '3 min',
    image: 'https://images.pexels.com/photos/3938022/pexels-photo-3938022.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '14.2k',
    comments: 67,
    tags: ['health', 'vaccination', 'public health'],
    modelResult: 'Suspicious',
  },
  {
    id: 9,
    title: 'Hydropower Plant Begins Commercial Operations',
    excerpt: 'Newly completed 200 MW hydroelectric facility begins generating power for national grid.',
    content: '<p>The 200-megawatt hydropower plant, developed with Chinese investment, commenced commercial operations. This facility will significantly increase Nepal\'s electricity generation capacity and support industrial growth.</p>',
    category: 'Breaking News',
    author: 'Santosh Kumar',
    publishedAt: '2 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3184317/pexels-photo-3184317.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '26.8k',
    comments: 134,
    tags: ['energy', 'hydropower', 'infrastructure'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 10,
    title: 'Education Ministry Launches Digital Learning Platform',
    excerpt: 'National online education platform provides free access to 50,000+ learning resources.',
    content: '<p>The Education Ministry launched a comprehensive digital learning platform offering over 50,000 educational resources. The platform aims to democratize access to quality education across rural and urban areas.</p>',
    category: 'Breaking News',
    author: 'Neha Singh',
    publishedAt: '2 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3862632/pexels-photo-3862632.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '22.4k',
    comments: 89,
    tags: ['education', 'digital', 'technology'],
    modelResult: 'Real',
  },
  {
    id: 11,
    title: 'Tourism Industry Rebounds with Record Visitor Numbers',
    excerpt: 'Nepal welcomes over 1 million tourists in first quarter, surpassing pre-pandemic levels.',
    content: '<p>Nepal\'s tourism sector showed remarkable recovery with over 1 million international visitors in the first quarter. Hotels and tourism operators report strong bookings across major destinations.</p>',
    category: 'Breaking News',
    author: 'Rajesh Poudel',
    publishedAt: '3 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/1488363/pexels-photo-1488363.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '19.3k',
    comments: 76,
    tags: ['tourism', 'economy', 'travel'],
    modelResult: 'Real',
  },
  {
    id: 12,
    title: 'Supreme Court Issues New Guidelines on Environmental Protection',
    excerpt: 'Landmark court ruling strengthens environmental regulations and corporate accountability.',
    content: '<p>The Supreme Court issued comprehensive guidelines mandating stricter environmental impact assessments for all major development projects. The ruling marks a significant step in strengthening environmental protection measures.</p>',
    category: 'Breaking News',
    author: 'Prakash Sharma',
    publishedAt: '3 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3184287/pexels-photo-3184287.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '17.6k',
    comments: 92,
    tags: ['law', 'environment', 'court'],
    modelResult: 'Real',
  },
  {
    id: 13,
    title: 'National Assembly Approves Digital Currency Pilot Project',
    excerpt: 'Nepal to begin testing blockchain-based digital currency system with central bank.',
    content: '<p>The National Assembly approved Nepal\'s digital currency pilot project involving the Nepal Rastra Bank. The initiative will explore blockchain technology implementation in financial transactions.</p>',
    category: 'Breaking News',
    author: 'Govind Thapa',
    publishedAt: '3 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3621524/pexels-photo-3621524.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '24.5k',
    comments: 145,
    tags: ['finance', 'technology', 'currency'],
    trending: true,
    modelResult: 'Real',
  },
  // Politics (13 articles)
  {
    id: 14,
    title: 'SAARC Members Agreement on Economic Integration Program',
    excerpt: 'Nepal leads regional economic cooperation initiative with South Asian neighboring nations.',
    content: '<p>Nepal successfully led negotiations on SAARC economic integration, resulting in agreement on strategic cooperation. The program aims to enhance trade, investment, and people-to-people exchanges across South Asia.</p>',
    category: 'Politics',
    author: 'Rakesh Kumar',
    publishedAt: '4 hours ago',
    readTime: '7 min',
    image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=1200',
    views: '22.8k',
    comments: 156,
    tags: ['politics', 'international', 'cooperation'],
    featured: true,
    modelResult: 'Real',
  },
  {
    id: 15,
    title: 'Parliament Passes Local Authority Empowerment Bill',
    excerpt: 'Landmark legislation grants expanded powers and budget autonomy to local governments.',
    content: '<p>The National Assembly passed the Local Authority Empowerment Bill granting municipalities increased financial and administrative authority. The legislation strengthens federalism and local governance frameworks.</p>',
    category: 'Politics',
    author: 'Neha Sharma',
    publishedAt: '6 hours ago',
    readTime: '6 min',
    image: 'https://images.pexels.com/photos/3184305/pexels-photo-3184305.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '18.9k',
    comments: 234,
    tags: ['politics', 'law', 'local government'],
    modelResult: 'Suspicious',
  },
  {
    id: 16,
    title: 'Nepal-India Border Dispute Resolution Committee Formed',
    excerpt: 'Joint committee established to address outstanding boundary demarcation issues.',
    content: '<p>Nepal and India formed a joint committee to resolve border demarcation disputes. The committee aims to clarify boundary lines and prevent future conflicts through peaceful dialogue mechanisms.</p>',
    category: 'Politics',
    author: 'Vijay Verma',
    publishedAt: '7 hours ago',
    readTime: '8 min',
    image: 'https://images.pexels.com/photos/3184427/pexels-photo-3184427.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '15.6k',
    comments: 189,
    tags: ['politics', 'borders', 'international'],
    modelResult: 'Fake',
  },
  {
    id: 17,
    title: 'Government Announces Anti-Corruption Task Force',
    excerpt: 'Special enforcement unit established to combat high-level corruption in government agencies.',
    content: '<p>The Prime Minister announced formation of a specialized anti-corruption task force with sweeping investigative powers. The initiative targets systemic corruption in public institutions and procurement processes.</p>',
    category: 'Politics',
    author: 'Sanjay Singh',
    publishedAt: '8 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '14.2k',
    comments: 145,
    tags: ['politics', 'corruption', 'enforcement'],
    modelResult: 'Real',
  },
  {
    id: 18,
    title: 'Constitutional Amendment Process Begins for Electoral Reforms',
    excerpt: 'Parliament initiates constitutional amendments to modernize electoral system and campaign regulations.',
    content: '<p>The constitutional amendment process began to reform Nepal\'s electoral framework. Proposed changes include campaign finance regulations, voter registration updates, and boundary redistribution methodology.</p>',
    category: 'Politics',
    author: 'Krishna Poulel',
    publishedAt: '9 hours ago',
    readTime: '7 min',
    image: 'https://images.pexels.com/photos/3184310/pexels-photo-3184310.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '19.5k',
    comments: 167,
    tags: ['politics', 'constitution', 'elections'],
    modelResult: 'Real',
  },
  {
    id: 19,
    title: 'Nepal Elected to UN Security Council Committee',
    excerpt: 'Country secures influential position on international peacekeeping and security council.',
    content: '<p>Nepal was elected to the UN Security Council Committee, representing South Asia and enhancing its role in international peacekeeping operations. The position reflects growing diplomatic influence of Nepal globally.</p>',
    category: 'Politics',
    author: 'Diplomat Anual Singh',
    publishedAt: '10 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3194521/pexels-photo-3194521.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '26.3k',
    comments: 178,
    tags: ['politics', 'united nations', 'international'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 20,
    title: 'Provincial Government Launches Rural Development Initiative',
    excerpt: 'Multi-billion rupee program aims to accelerate development in remote mountain communities.',
    content: '<p>Provincial governments launched a comprehensive rural development program targeting remote regions. The initiative focuses on infrastructure, education, and healthcare services expansion in underserved areas.</p>',
    category: 'Politics',
    author: 'Prakash Sharma',
    publishedAt: '11 hours ago',
    readTime: '6 min',
    image: 'https://images.pexels.com/photos/3184315/pexels-photo-3184315.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '17.8k',
    comments: 91,
    tags: ['politics', 'development', 'rural'],
    modelResult: 'Real',
  },
  {
    id: 21,
    title: 'Civil Service Examinations Conducted Nationwide',
    excerpt: 'Over 200,000 candidates compete for government positions across all administrative levels.',
    content: '<p>Annual civil service examinations were conducted across Nepal with over 200,000 candidates competing. The competitive examination determines selection for government positions at various administrative tiers.</p>',
    category: 'Politics',
    author: 'Govind Thapa',
    publishedAt: '12 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3862643/pexels-photo-3862643.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '13.4k',
    comments: 67,
    tags: ['politics', 'civil service', 'government'],
    modelResult: 'Real',
  },
  {
    id: 22,
    title: 'Political Leaders Meet on Economic Recovery Framework',
    excerpt: 'Cross-party consensus emerges on fiscal stimulus and business investment incentives.',
    content: '<p>Major political party leaders convened to discuss post-pandemic economic recovery strategies. Consensus emerged on fiscal stimulus measures, tax incentives, and business development programs.</p>',
    category: 'Politics',
    author: 'Rajendra Bhatta',
    publishedAt: '13 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3184287/pexels-photo-3184287.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '16.2k',
    comments: 102,
    tags: ['politics', 'economy', 'cooperation'],
    modelResult: 'Suspicious',
  },
  {
    id: 23,
    title: 'Women\'s Representation in Government Reaches 40%',
    excerpt: 'Landmark achievement in gender equality with women occupying significant government positions.',
    content: '<p>Women\'s representation in government reached the historic 40% mark across all administrative levels. The achievement reflects successful implementation of gender equality policies and quota systems.</p>',
    category: 'Politics',
    author: 'Sharmila Kumari',
    publishedAt: '14 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3807494/pexels-photo-3807494.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '21.7k',
    comments: 156,
    tags: ['politics', 'gender equality', 'government'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 24,
    title: 'National Security Strategy Released by Government',
    excerpt: 'Comprehensive defense and security framework addresses modern threats and regional challenges.',
    content: '<p>The government released its updated National Security Strategy focusing on cybersecurity, terrorism prevention, and border security. The strategy reflects evolving security challenges in the region.</p>',
    category: 'Politics',
    author: 'Col. Dipendra Singh',
    publishedAt: '15 hours ago',
    readTime: '7 min',
    image: 'https://images.pexels.com/photos/3414521/pexels-photo-3414521.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '18.9k',
    comments: 123,
    tags: ['politics', 'security', 'defense'],
    modelResult: 'Real',
  },
  {
    id: 25,
    title: 'Transitional Justice Commission Issues Five-Year Implementation Plan',
    excerpt: 'Roadmap established for truth and reconciliation process addressing conflict legacy.',
    content: '<p>The Transitional Justice Commission released a comprehensive five-year implementation plan addressing post-conflict accountability. The plan includes truth commissions, victim reparations, and institutional reforms.</p>',
    category: 'Politics',
    author: 'Kamal Gurung',
    publishedAt: '16 hours ago',
    readTime: '6 min',
    image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '14.6k',
    comments: 89,
    tags: ['politics', 'justice', 'reconciliation'],
    modelResult: 'Real',
  },
  {
    id: 26,
    title: 'Parliament Committee Proposes Healthcare Reform Bill',
    excerpt: 'Comprehensive legislation aims to universalize healthcare access and improve service delivery.',
    content: '<p>A parliamentary health committee proposed comprehensive healthcare reform legislation. The bill aims to expand universal healthcare coverage and establish primary health centers in all rural districts.</p>',
    category: 'Politics',
    author: 'Dr. Sundar Bhati',
    publishedAt: '17 hours ago',
    readTime: '6 min',
    image: 'https://images.pexels.com/photos/3938042/pexels-photo-3938042.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '20.1k',
    comments: 134,
    tags: ['politics', 'healthcare', 'legislation'],
    modelResult: 'Real',
  },
  // Technology (13 articles)
  {
    id: 27,
    title: 'Artificial Intelligence Training Center Opens in Kathmandu',
    excerpt: 'State-of-the-art facility provides AI and machine learning courses for tech professionals.',
    content: '<p>A new Artificial Intelligence training center officially opened in Kathmandu, offering comprehensive AI and machine learning courses. The facility aims to develop technical talent for Nepal\'s growing tech sector.</p>',
    category: 'Technology',
    author: 'Dr. Sarah Chen',
    publishedAt: '2 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3825581/pexels-photo-3825581.jpeg?auto=compress&cs=tinysrgb&w=1200',
    views: '15.2k',
    comments: 89,
    tags: ['technology', 'artificial intelligence', 'training'],
    trending: true,
    featured: true,
    modelResult: 'Real',
  },
  {
    id: 28,
    title: '5G Network Launch Announced by Mobile Providers',
    excerpt: 'Nepal enters new era of wireless technology with 5G network deployment in major cities.',
    content: '<p>Mobile service providers announced imminent 5G network deployment starting in Kathmandu and Pokhara. The next-generation network technology will enable faster data speeds and support IoT expansion.</p>',
    category: 'Technology',
    author: 'Kiran Sharma',
    publishedAt: '3 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/2182863/pexels-photo-2182863.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '12.3k',
    comments: 28,
    tags: ['technology', '5G', 'infrastructure'],
    modelResult: 'Real',
  },
  {
    id: 29,
    title: 'E-Commerce Revolution Doubles Online Shopping Annually',
    excerpt: 'Digital retail sector experiences explosive growth with year-over-year transaction doubling.',
    content: '<p>Nepal\'s e-commerce sector witnessed explosive 100% growth in annual transactions. Online shopping platforms report rapid user base expansion across rural and urban markets.</p>',
    category: 'Technology',
    author: 'Raj Singh',
    publishedAt: '5 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '28.4k',
    comments: 112,
    tags: ['e-commerce', 'technology', 'online'],
    featured: true,
    modelResult: 'Suspicious',
  },
  {
    id: 30,
    title: 'Cybersecurity Unit Established by Government',
    excerpt: 'National cyber security task force launches to protect digital infrastructure and citizen data.',
    content: '<p>Government established a dedicated cybersecurity unit to combat rising cyber threats and protect national digital infrastructure. The agency will coordinate defense against cyberattacks and data breaches.</p>',
    category: 'Technology',
    author: 'Amar Kumar',
    publishedAt: '6 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '19.7k',
    comments: 67,
    tags: ['cybersecurity', 'technology', 'government'],
    modelResult: 'Real',
  },
  {
    id: 31,
    title: 'Cloud Computing Infrastructure Developed by Tech Companies',
    excerpt: 'Private companies build first homegrown cloud data centers reducing reliance on foreign servers.',
    content: '<p>Nepali tech companies developed indigenous cloud computing infrastructure and data centers. The initiative aims to reduce dependence on foreign cloud services and enhance data sovereignty.</p>',
    category: 'Technology',
    author: 'Bikram Thapa',
    publishedAt: '7 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3928874/pexels-photo-3928874.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '16.8k',
    comments: 94,
    tags: ['cloud', 'technology', 'infrastructure'],
    modelResult: 'Fake',
  },
  {
    id: 32,
    title: 'Blockchain Technology Adoption Growing in Finance Sector',
    excerpt: 'Banks and financial institutions piloting distributed ledger technology for transactions.',
    content: '<p>Nepal\'s banking sector began implementing blockchain technology for secure financial transactions. Multiple banks launched pilot projects to test cryptocurrency and smart contract applications.</p>',
    category: 'Technology',
    author: 'Sanjeev Poudel',
    publishedAt: '8 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3633551/pexels-photo-3633551.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '21.4k',
    comments: 156,
    tags: ['blockchain', 'finance', 'technology'],
    modelResult: 'Real',
  },
  {
    id: 33,
    title: 'Mobile App Development Bootcamp Launches for Startups',
    excerpt: 'Accelerator program mentors aspiring entrepreneurs in mobile application development.',
    content: '<p>A comprehensive mobile app development bootcamp launched for Nepali startups and entrepreneurs. The program provides technical mentorship, funding, and market access for developing innovative applications.</p>',
    category: 'Technology',
    author: 'Priya Lamichhane',
    publishedAt: '9 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '13.2k',
    comments: 78,
    tags: ['technology', 'startups', 'development'],
    modelResult: 'Real',
  },
  {
    id: 34,
    title: 'Internet Bandwidth Expansion Improves Connectivity',
    excerpt: 'New undersea fiber optic cable increases internet capacity and reduces access costs.',
    content: '<p>Nepal connected to new undersea fiber optic cables expanding internet bandwidth significantly. The expansion enables faster internet speeds and reduced connectivity costs nationwide.</p>',
    category: 'Technology',
    author: 'Govind Bajracharya',
    publishedAt: '10 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/226567/pexels-photo-226567.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '18.7k',
    comments: 89,
    tags: ['technology', 'internet', 'infrastructure'],
    modelResult: 'Real',
  },
  {
    id: 35,
    title: 'Fintech Startups Secure Record Funding in 2024',
    excerpt: 'Financial technology companies attract unprecedented foreign investment and venture capital.',
    content: '<p>Nepali fintech startups secured record venture capital funding in 2024. Foreign investors showed strong interest in digital payment, lending, and insurance technology companies.</p>',
    category: 'Technology',
    author: 'Nikhil Sharma',
    publishedAt: '11 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '25.1k',
    comments: 145,
    tags: ['fintech', 'startups', 'investment'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 36,
    title: 'Internet of Things (IoT) Applications Expand in Agriculture',
    excerpt: 'Smart farming technology helps Nepali farmers optimize crop production and resource usage.',
    content: '<p>IoT sensors and smart farming technology adoption is growing among Nepali farmers. These applications monitor soil conditions, weather patterns, and irrigation systems improving crop yields.</p>',
    category: 'Technology',
    author: 'Kancha Lama',
    publishedAt: '12 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/1537904/pexels-photo-1537904.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '14.6k',
    comments: 67,
    tags: ['IoT', 'agriculture', 'technology'],
    modelResult: 'Suspicious',
  },
  {
    id: 37,
    title: 'Virtual Reality Applications Transform Education Delivery',
    excerpt: 'Educational institutions adopt VR technology for immersive learning experiences.',
    content: '<p>Educational institutions began implementing virtual reality applications for interactive learning. VR classrooms enable students to explore historical sites, conduct virtual scientific experiments, and practice skills.</p>',
    category: 'Technology',
    author: 'Dr. Anita Gurung',
    publishedAt: '13 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3862575/pexels-photo-3862575.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '19.3k',
    comments: 102,
    tags: ['virtual reality', 'education', 'technology'],
    modelResult: 'Real',
  },
  {
    id: 38,
    title: 'Software Companies Report Strong Export Growth',
    excerpt: 'Nepali IT firms increase software and service exports to international markets.',
    content: '<p>Nepali software companies reported 45% growth in international exports over the past year. Strong demand from US and European markets drives outsourcing and IT services expansion.</p>',
    category: 'Technology',
    author: 'Rishi Shrestha',
    publishedAt: '14 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3194521/pexels-photo-3194521.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '22.8k',
    comments: 134,
    tags: ['software', 'exports', 'technology'],
    modelResult: 'Real',
  },
  {
    id: 39,
    title: 'Quantum Computing Research Initiative Announced',
    excerpt: 'Government funds research partnership with international institutions on quantum technologies.',
    content: '<p>Government announced a quantum computing research initiative partnering with international technology institutions. The program aims to develop quantum solutions for cryptography and complex calculations.</p>',
    category: 'Technology',
    author: 'Prof. Ramesh Bhatta',
    publishedAt: '15 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3621524/pexels-photo-3621524.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '17.2k',
    comments: 78,
    tags: ['quantum', 'research', 'technology'],
    modelResult: 'Real',
  },
  // Business (13 articles)
  {
    id: 40,
    title: 'Nepal Stock Exchange Reports Record Dividend Payments',
    excerpt: 'Listed companies distribute record dividends totaling billions as profits surge.',
    content: '<p>Nepal Stock Exchange listed companies announced record dividend distributions totaling billions of rupees. Strong corporate performance and investor returns reflect growing market confidence and economic growth.</p>',
    category: 'Business',
    author: 'Raj Kumar',
    publishedAt: '5 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/159888/pexels-photo-159888.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '25.1k',
    comments: 67,
    tags: ['business', 'stocks', 'investment'],
    modelResult: 'Real',
  },
  {
    id: 41,
    title: 'Nepal Issues First Green Bond in International Markets',
    excerpt: 'Government raises capital for environmental projects through green security issuance.',
    content: '<p>Nepal government successfully issued its first green bond in international markets, raising funding for environmental projects. The $100 million bond attracted strong investor interest and ESG-focused funds.</p>',
    category: 'Business',
    author: 'Priya Sharma',
    publishedAt: '6 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '16.8k',
    comments: 94,
    tags: ['business', 'environment', 'economy'],
    modelResult: 'Real',
  },
  {
    id: 42,
    title: 'Nepal-Bangladesh Trade Agreement Signed',
    excerpt: 'New bilateral commerce pact reduces tariffs and expands business opportunities.',
    content: '<p>Nepal and Bangladesh signed a comprehensive trade agreement reducing tariffs and facilitating business cooperation. The pact covers agriculture, manufacturing, technology, and services sectors.</p>',
    category: 'Business',
    author: 'Amar Smith',
    publishedAt: '1 day ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3184649/pexels-photo-3184649.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '21.4k',
    comments: 156,
    tags: ['business', 'trade', 'international'],
    modelResult: 'Real',
  },
  {
    id: 43,
    title: 'Tech Startups Rise in Nepal Venture Capital Ecosystem',
    excerpt: 'Fifty percent increase in startup funding marks vibrant entrepreneurship growth.',
    content: '<p>Nepal\'s startup sector witnessed 50% growth in venture capital investments this year. Tech entrepreneurs report strong domestic and international investor interest in innovation-based business models.</p>',
    category: 'Business',
    author: 'Nicole Hayes',
    publishedAt: '1 day ago',
    readTime: '6 min',
    image: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '13.2k',
    comments: 78,
    tags: ['startups', 'investment', 'business'],
    modelResult: 'Suspicious',
  },
  {
    id: 44,
    title: 'Manufacturing Sector Expands Export Markets',
    excerpt: 'Nepali manufacturers increase international sales to South Asian and Asian markets.',
    content: '<p>Nepal\'s manufacturing sector expanded exports to new markets in South and Southeast Asia. Sectors including textiles, pashmina, and handicrafts report strong international demand and revenue growth.</p>',
    category: 'Business',
    author: 'Govind Poudel',
    publishedAt: '1 day ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3836298/pexels-photo-3836298.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '18.3k',
    comments: 89,
    tags: ['manufacturing', 'exports', 'business'],
    modelResult: 'Real',
  },
  {
    id: 45,
    title: 'Tourism Industry Recovery Exceeds Expectations',
    excerpt: 'Foreign exchange earnings from tourism surge as visitor numbers hit record highs.',
    content: '<p>Tourism sector foreign exchange earnings surged as international visitor numbers reached record highs. Hotels, trekking companies, and tour operators report unprecedented bookings and revenues.</p>',
    category: 'Business',
    author: 'Rajesh Poudel',
    publishedAt: '1 day ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/1488363/pexels-photo-1488363.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '26.4k',
    comments: 112,
    tags: ['tourism', 'economy', 'travel'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 46,
    title: 'Agricultural Exports Generate Record Revenue',
    excerpt: 'Organic and specialty crops drive agriculture sector growth and farmer income.',
    content: '<p>Nepal\'s agricultural exports generated record revenue through organic produce and specialty crops. Farmers adopt improved cultivation techniques and achieve premium prices in international markets.</p>',
    category: 'Business',
    author: 'Kancha Sherpa',
    publishedAt: '1 day ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '14.7k',
    comments: 67,
    tags: ['agriculture', 'exports', 'farming'],
    modelResult: 'Fake',
  },
  {
    id: 47,
    title: 'Banking Sector Mergers Create Financial Consolidation',
    excerpt: 'Multiple bank mergers strengthen financial sector competitiveness and stability.',
    content: '<p>Several bank mergers consolidated Nepal\'s banking sector, creating larger financial institutions. The consolidation improves financial stability and enables banks to compete globally.</p>',
    category: 'Business',
    author: 'Deepak Adhikari',
    publishedAt: '2 days ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3184305/pexels-photo-3184305.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '15.9k',
    comments: 78,
    tags: ['banking', 'finance', 'business'],
    modelResult: 'Real',
  },
  {
    id: 48,
    title: 'Insurance Industry Expands Health and Life Products',
    excerpt: 'Rising middle class drives demand for insurance coverage and financial protection.',
    content: '<p>Insurance companies expanded product portfolios with innovative health and life coverage options. Rising income levels and awareness drive strong demand for insurance and financial protection services.</p>',
    category: 'Business',
    author: 'Sunita Poudel',
    publishedAt: '2 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '12.1k',
    comments: 54,
    tags: ['insurance', 'finance', 'business'],
    modelResult: 'Real',
  },
  {
    id: 49,
    title: 'Real Estate Market boom in Kathmandu Valley',
    excerpt: 'Property prices surge amid strong demand from domestic and foreign investors.',
    content: '<p>Kathmandu Valley real estate market experienced significant growth with property prices rising 30% annually. Strong demand from investors, expatriates, and residential buyers drives market expansion.</p>',
    category: 'Business',
    author: 'Bijay Shrestha',
    publishedAt: '2 days ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/1453504/pexels-photo-1453504.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '22.8k',
    comments: 145,
    tags: ['real estate', 'investment', 'property'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 50,
    title: 'Retail Chain Expansion Creates Thousands of Jobs',
    excerpt: 'Major retail companies open new stores and shopping centers nationwide.',
    content: '<p>Major retail chains expanded operations opening new shopping centers and stores across Nepal. The retail expansion created thousands of employment opportunities in sales, management, and logistics sectors.</p>',
    category: 'Business',
    author: 'Mahesh Khadka',
    publishedAt: '2 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3887622/pexels-photo-3887622.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '17.3k',
    comments: 92,
    tags: ['retail', 'employment', 'business'],
    modelResult: 'Suspicious',
  },
  {
    id: 51,
    title: 'FDI Inflows Reach All-Time High',
    excerpt: 'Foreign direct investment exceeds two billion dollars driving economic growth.',
    content: '<p>Foreign direct investment inflows reached all-time high surpassing $2 billion in annual flows. Investors target infrastructure, energy, technology, and tourism sectors recognizing Nepal\'s growth potential.</p>',
    category: 'Business',
    author: 'Ramesh Bhatt',
    publishedAt: '2 days ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3194521/pexels-photo-3194521.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '20.6k',
    comments: 123,
    tags: ['investment', 'FDI', 'economy'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 52,
    title: 'Cooperative Sector Growth Empowers Rural Communities',
    excerpt: 'Agricultural and financial cooperatives expand services and membership nationwide.',
    content: '<p>Nepal\'s cooperative sector expanded significantly with agricultural and financial cooperatives increasing membership and services. Cooperatives provide credit, input distribution, and product marketing for rural communities.</p>',
    category: 'Business',
    author: 'Pratap Singh',
    publishedAt: '2 days ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3807517/pexels-photo-3807517.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '13.8k',
    comments: 71,
    tags: ['cooperative', 'rural', 'business'],
    modelResult: 'Real',
  },
  // Sports (13 articles)
  {
    id: 53,
    title: 'Nepal Cricket Team Wins ICC Qualifier Tournament',
    excerpt: 'National cricket team defeats regional rivals to secure tournament championship.',
    content: '<p>Nepal\'s national cricket team demonstrated exceptional skill defeating regional rivals in the ICC qualifier tournament final. The victory secured Nepal\'s participation in international cricket championships.</p>',
    category: 'Sports',
    author: 'Marcus Johnson',
    publishedAt: '2 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3621519/pexels-photo-3621519.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '34.6k',
    comments: 267,
    tags: ['cricket', 'sports', 'victory'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 54,
    title: 'Nepal Advances in SAARC Games Medal Count',
    excerpt: 'Athletes secure 35 gold medals advancing Nepal higher on regional sports standings.',
    content: '<p>Nepali athletes advanced significantly in the SAARC Games medal standings, securing 35 gold medals. Strong performances in athletics, weightlifting, and martial arts boosted Nepal\'s regional sports standing.</p>',
    category: 'Sports',
    author: 'Thomas Anderson',
    publishedAt: '3 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/2747225/pexels-photo-2747225.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '28.9k',
    comments: 145,
    tags: ['SAARC', 'sports', 'Nepal'],
    modelResult: 'Real',
  },
  {
    id: 55,
    title: 'International Mountain Marathon Held in Nepal',
    excerpt: 'Himalayan Sports Cup attracts runners from 40 countries to Nepal.',
    content: '<p>The international Himalayan Sports Marathon hosted athletes from over 40 countries running through Nepal\'s mountain terrain. The event promoted Nepal\'s natural beauty and adventure sports tourism globally.</p>',
    category: 'Sports',
    author: 'Lauren Cole',
    publishedAt: '4 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/358154/pexels-photo-358154.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '41.2k',
    comments: 312,
    tags: ['sports', 'international', 'mountaineering'],
    modelResult: 'Real',
  },
  {
    id: 56,
    title: 'Young Nepali Athlete Breaks International Records',
    excerpt: 'Eighteen-year-old athlete achieves national and regional performance records.',
    content: '<p>An eighteen-year-old Nepali athlete broke national and regional sports records in track and field, earning international recognition. The achievement showcases Nepal\'s emerging athletic talent and potential champions.</p>',
    category: 'Sports',
    author: 'Daniel Foster',
    publishedAt: '5 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/159573/pexels-photo-159573.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '19.8k',
    comments: 98,
    tags: ['sports', 'talent', 'records'],
    modelResult: 'Real',
  },
  {
    id: 57,
    title: 'Nepal Football Team Qualifies for Asian Championship',
    excerpt: 'National football team advances to continental championship tournament.',
    content: '<p>Nepal\'s national football team qualified for the Asian Championship tournament defeating qualified opponents. The qualification marks significant progress for Nepali football development and competitiveness.</p>',
    category: 'Sports',
    author: 'Eric Martinez',
    publishedAt: '6 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3621519/pexels-photo-3621519.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '16.4k',
    comments: 78,
    tags: ['football', 'sports', 'championship'],
    modelResult: 'Suspicious',
  },
  {
    id: 58,
    title: 'Volleyball Team Wins Regional Championship',
    excerpt: 'Nepali women\'s volleyball team captures regional tournament title.',
    content: '<p>Nepal\'s women\'s volleyball team won the regional championship demonstrating strong technical skills and teamwork. The victory represents a major achievement for Nepali women\'s sports development.</p>',
    category: 'Sports',
    author: 'Jessica Wong',
    publishedAt: '7 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/2747225/pexels-photo-2747225.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '13.7k',
    comments: 67,
    tags: ['volleyball', 'women sports', 'championship'],
    modelResult: 'Real',
  },
  {
    id: 59,
    title: 'Mountaineering Season Records Everest Summit Success',
    excerpt: 'Record number of climbers successfully summit Mount Everest from Nepal.',
    content: '<p>Mount Everest climbing season recorded exceptional success with record number of climbers reaching the summit through Nepal\'s routes. The season generated significant revenue for Nepal and enhanced international climbing reputation.</p>',
    category: 'Sports',
    author: 'Pemba Sherpa',
    publishedAt: '8 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3807517/pexels-photo-3807517.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '29.5k',
    comments: 145,
    tags: ['mountaineering', 'everest', 'sports'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 60,
    title: 'Boxing Federation Develops New Training Center',
    excerpt: 'State-of-the-art boxing facility opens for elite athlete development.',
    content: '<p>Nepal\'s boxing federation inaugurated a state-of-the-art training facility for boxer development. The center provides modern equipment, professional coaching, and international competition preparation.</p>',
    category: 'Sports',
    author: 'Ramesh Yadav',
    publishedAt: '9 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3807694/pexels-photo-3807694.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '12.3k',
    comments: 54,
    tags: ['boxing', 'sports', 'training'],
    modelResult: 'Real',
  },
  {
    id: 61,
    title: 'Nepal Hosts Asian Wrestling Championship',
    excerpt: 'International wrestling tournament brings elite competitors to Kathmandu.',
    content: '<p>Nepal successfully hosted the Asian Wrestling Championship attracting elite wrestlers from across Asia. The tournament showcased Nepal\'s sports infrastructure and attracted international tourist attention.</p>',
    category: 'Sports',
    author: 'Sunil Lama',
    publishedAt: '10 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3807704/pexels-photo-3807704.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '15.2k',
    comments: 89,
    tags: ['wrestling', 'sports', 'championship'],
    modelResult: 'Fake',
  },
  {
    id: 62,
    title: 'Cycling Tour Across Nepal Attracts International Participants',
    excerpt: 'Multi-week cycling event showcases Nepal\'s scenic routes and tourism.',
    content: '<p>The international cycling tour across Nepal attracted hundreds of cyclists from multiple countries. The event promoted Nepal\'s beautiful natural scenery and adventure tourism globally.</p>',
    category: 'Sports',
    author: 'Kristina Hansen',
    publishedAt: '11 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/1298161/pexels-photo-1298161.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '18.6k',
    comments: 102,
    tags: ['cycling', 'sports', 'tourism'],
    modelResult: 'Real',
  },
  {
    id: 63,
    title: 'Badminton Players Achieve Career Best Rankings',
    excerpt: 'Nepali badminton professionals climb international rankings.',
    content: '<p>Nepali badminton players improved international rankings achieving personal career bests. Consistent international tournament participation resulted in enhanced global rankings and sponsorship opportunities.</p>',
    category: 'Sports',
    author: 'Anita Karim',
    publishedAt: '12 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3807683/pexels-photo-3807683.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '11.8k',
    comments: 61,
    tags: ['badminton', 'sports', 'ranking'],
    modelResult: 'Real',
  },
  {
    id: 64,
    title: 'Sports Complex Expansion Supports Youth Development',
    excerpt: 'Government funds sports facilities nationwide to nurture athletic talent.',
    content: '<p>Government expanded sports complex infrastructure nationwide supporting youth athletic development. New facilities provide training grounds, coaching, and competitive opportunities for emerging sports talent.</p>',
    category: 'Sports',
    author: 'Vikram Thapa',
    publishedAt: '13 hours ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3807694/pexels-photo-3807694.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '14.5k',
    comments: 78,
    tags: ['sports', 'development', 'youth'],
    modelResult: 'Suspicious',
  },
  {
    id: 65,
    title: 'Taekwondo Federation Produces Olympic Qualifiers',
    excerpt: 'Elite athletes secure qualification for international Olympic competition.',
    content: '<p>Nepal\'s taekwondo federation produced athletes qualifying for international Olympic competitions. The achievement reflects improved training standards and emerging international competitiveness in martial arts.</p>',
    category: 'Sports',
    author: 'Michael Chang',
    publishedAt: '14 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3807698/pexels-photo-3807698.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '17.2k',
    comments: 91,
    tags: ['taekwondo', 'olympics', 'sports'],
    modelResult: 'Real',
  },
  // Entertainment (13 articles)
  {
    id: 66,
    title: 'Nepali Cinema Gains International Recognition',
    excerpt: 'Nepal films secure international distribution deals and festival selections.',
    content: '<p>Nepali cinema gained significant international recognition with films securing distribution deals in Europe and America. Several Nepal-made films were selected for international film festivals receiving critical acclaim.</p>',
    category: 'Entertainment',
    author: 'Sophia Mitchell',
    publishedAt: '1 day ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/2034994/pexels-photo-2034994.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '24.5k',
    comments: 134,
    tags: ['cinema', 'film', 'Nepal'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 67,
    title: 'Kathmandu Music Festival Attracts World-Class Artists',
    excerpt: 'International music festival showcases genre diversity and Nepali talent.',
    content: '<p>The Kathmandu Music Festival attracted world-class musicians from multiple countries performing diverse musical genres. The festival promoted Nepal\'s vibrant music culture and creative talent globally.</p>',
    category: 'Entertainment',
    author: 'Christopher Reid',
    publishedAt: '1 day ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/1047442/pexels-photo-1047442.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '18.7k',
    comments: 89,
    tags: ['music', 'festival', 'entertainment'],
    modelResult: 'Real',
  },
  {
    id: 68,
    title: 'Nepali Actress Wins International Motion Picture Award',
    excerpt: 'Leading actress honored for outstanding movie performance at prestigious ceremony.',
    content: '<p>A Nepali actress won an international film award for outstanding acting performance in an acclaimed motion picture. The recognition marked a significant achievement for Nepali talent in international cinema.</p>',
    category: 'Entertainment',
    author: 'Amanda Price',
    publishedAt: '1 day ago',
    readTime: '3 min',
    image: 'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '31.2k',
    comments: 156,
    tags: ['actress', 'film', 'awards'],
    modelResult: 'Real',
  },
  {
    id: 69,
    title: 'Nepali Television Series Receives International Platform Release',
    excerpt: 'Popular local series secures distribution on major streaming platforms.',
    content: '<p>A successful Nepali television series received international distribution on major streaming platforms reaching global audiences. The series represents triumph of Nepali television production quality and storytelling.</p>',
    category: 'Entertainment',
    author: 'Gregory White',
    publishedAt: '1 day ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/2156881/pexels-photo-2156881.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '14.6k',
    comments: 72,
    tags: ['television', 'entertainment', 'series'],
    modelResult: 'Real',
  },
  {
    id: 70,
    title: 'Comedy Festival Brings Laughter and Entertainment',
    excerpt: 'Annual comedy festival features local and international stand-up performers.',
    content: '<p>Nepal\'s comedy festival brought together local and international stand-up performers entertaining audiences with diverse humor. The festival promoted Nepal\'s comedy scene and emerging comedians globally.</p>',
    category: 'Entertainment',
    author: 'Rajesh Poudel',
    publishedAt: '2 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/2156881/pexels-photo-2156881.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '16.3k',
    comments: 87,
    tags: ['comedy', 'entertainment', 'festival'],
    modelResult: 'Real',
  },
  {
    id: 71,
    title: 'Dance Performance Company Wins International Choreography Award',
    excerpt: 'Nepali dance troupe honored for innovative choreography and performance.',
    content: '<p>A Nepali dance performance company won international recognition for innovative choreography blending traditional and contemporary dance. The award acknowledged excellence in artistic expression and cultural representation.</p>',
    category: 'Entertainment',
    author: 'Isabella Rossi',
    publishedAt: '2 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3621531/pexels-photo-3621531.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '12.8k',
    comments: 67,
    tags: ['dance', 'art', 'performance'],
    modelResult: 'Suspicious',
  },
  {
    id: 72,
    title: 'Folk Music Festival Celebrates Traditional Heritage',
    excerpt: 'Annual event showcases Nepal\'s diverse traditional music and instruments.',
    content: '<p>Nepal\'s folk music festival celebrated traditional heritage with performances by renowned musicians. The festival preserved and promoted Nepal\'s diverse musical traditions and cultural identity.</p>',
    category: 'Entertainment',
    author: 'Govind Pariyar',
    publishedAt: '2 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/1281365/pexels-photo-1281365.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '13.2k',
    comments: 72,
    tags: ['folk music', 'culture', 'heritage'],
    modelResult: 'Real',
  },
  {
    id: 73,
    title: 'Theater Production Company Stages Award-Winning Plays',
    excerpt: 'Multiple theatrical productions receive critical acclaim and audience appreciation.',
    content: '<p>Nepali theater production companies staged award-winning plays receiving critical acclaim. Professional theatrical productions demonstrated advancement of Nepal\'s performing arts and dramatic storytelling tradition.</p>',
    category: 'Entertainment',
    author: 'Sunita Lamichhane',
    publishedAt: '2 days ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3823517/pexels-photo-3823517.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '15.6k',
    comments: 82,
    tags: ['theater', 'drama', 'performance'],
    modelResult: 'Real',
  },
  {
    id: 74,
    title: 'Animation Studio Creates Award-Winning Film',
    excerpt: 'Nepali animation house produces film earning international recognition and awards.',
    content: '<p>A Nepali animation studio created an award-winning animated feature film receiving international recognition. The production demonstrated creative talent and technical sophistication in animation and visual storytelling.</p>',
    category: 'Entertainment',
    author: 'Bikram Adhikari',
    publishedAt: '2 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3862575/pexels-photo-3862575.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '18.2k',
    comments: 94,
    tags: ['animation', 'film', 'creativity'],
    modelResult: 'Real',
  },
  {
    id: 75,
    title: 'Reality Television Show Finds Success and Viewership',
    excerpt: 'Popular reality entertainment series attracts large audiences.',
    content: '<p>A Nepali reality television series gained massive popularity and high viewership ratings. The show\'s success demonstrates strong local demand for entertainment content and talent showcase programming.</p>',
    category: 'Entertainment',
    author: 'Priya Sharma',
    publishedAt: '2 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/2156845/pexels-photo-2156845.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '22.7k',
    comments: 127,
    tags: ['reality tv', 'entertainment', 'media'],
    trending: true,
    modelResult: 'Real',
  },
  {
    id: 76,
    title: 'Film Festival Showcases Emerging Directors',
    excerpt: 'Annual cinema festival promotes new filmmaking talent and diverse perspectives.',
    content: '<p>Nepal\'s film festival showcased emerging directors and independent filmmakers. The platform supported entrepreneurial filmmakers and diverse storytelling providing launch venue for creative talent.</p>',
    category: 'Entertainment',
    author: 'Vikram Poudel',
    publishedAt: '3 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/2034994/pexels-photo-2034994.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '14.1k',
    comments: 71,
    tags: ['film', 'festival', 'directors'],
    modelResult: 'Fake',
  },
  {
    id: 77,
    title: 'Music Producer Collaborates with International Artists',
    excerpt: 'Nepali musician creates international collaboration producing chart hits.',
    content: '<p>A Nepali music producer collaborated with international artists on musical projects achieving chart success. The collaboration showcased Nepal\'s musical talent and international appeal.</p>',
    category: 'Entertainment',
    author: 'Rahul Paudel',
    publishedAt: '3 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3675857/pexels-photo-3675857.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '16.8k',
    comments: 89,
    tags: ['music', 'collaboration', 'artist'],
    modelResult: 'Real',
  },
  {
    id: 78,
    title: 'Nepali Artist Exhibition Attracts International Collectors',
    excerpt: 'Contemporary art showcase features Nepali artists gaining international attention.',
    content: '<p>Nepali contemporary artists exhibited works in prestigious galleries attracting international collectors and art enthusiasts. The exhibition promoted Nepal\'s artistic talent and modern art movement globally.</p>',
    category: 'Entertainment',
    author: 'Deepa Karmacharya',
    publishedAt: '3 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3621627/pexels-photo-3621627.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '13.4k',
    comments: 67,
    tags: ['art', 'exhibition', 'contemporary'],
    modelResult: 'Suspicious',
  },
  // Science (13 articles)
  {
    id: 79,
    title: 'Tibetan Plateau Ecosystem New Species Discovery',
    excerpt: 'Scientists discover new wildlife species in Himalayan region research expedition.',
    content: '<p>Scientists conducting research in the Tibetan Plateau region discovered new wildlife species previously unknown to science. The discovery enhances understanding of high-altitude ecosystem biodiversity and adaptation mechanisms.</p>',
    category: 'Science',
    author: 'Prof. Elinor Basse',
    publishedAt: '6 hours ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/796206/pexels-photo-796206.jpeg?auto=compress&cs=tinysrgb&w=1200',
    views: '31.5k',
    comments: 203,
    tags: ['science', 'exploration', 'discovery'],
    trending: true,
    featured: true,
    modelResult: 'Real',
  },
  {
    id: 80,
    title: 'Nepali Botanist Discovers Medicinal Plants in Amazon Rainforest',
    excerpt: 'Nepali researcher identifies new pharmaceutical plant species with medicinal properties.',
    content: '<p>A Nepali botanist discovered new medicinal plant species in the Amazon rainforest with potential pharmaceutical applications. The discovery could lead to development of treatments for various diseases.</p>',
    category: 'Science',
    author: 'Dr. Patricia Lewis',
    publishedAt: '1 day ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/1537904/pexels-photo-1537904.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '16.4k',
    comments: 112,
    tags: ['science', 'botany', 'medicine'],
    modelResult: 'Real',
  },
  {
    id: 81,
    title: 'Himalayan Climate Change Research Published Internationally',
    excerpt: 'Nepali climate scientists\' research findings accepted by international journals.',
    content: '<p>Nepali climate scientists published groundbreaking research on Himalayan climate change in top international publications. The research provides critical data on glacier melting and climate impacts.</p>',
    category: 'Science',
    author: 'Dr. William Chang',
    publishedAt: '1 day ago',
    readTime: '6 min',
    image: 'https://images.pexels.com/photos/414837/pexels-photo-414837.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '22.1k',
    comments: 178,
    tags: ['science', 'climate', 'research'],
    modelResult: 'Real',
  },
  {
    id: 82,
    title: 'Cancer Treatment Breakthrough Developed by Nepali Doctors',
    excerpt: 'Medical researchers develop innovative cancer therapy technique.',
    content: '<p>Nepali medical researchers developed innovative cancer treatment methodology showing promising results in clinical trials. The breakthrough could provide alternative therapy options for cancer patients.</p>',
    category: 'Science',
    author: 'Dr. Rachel Green',
    publishedAt: '1 day ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3938022/pexels-photo-3938022.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '13.8k',
    comments: 95,
    tags: ['science', 'medicine', 'discovery'],
    modelResult: 'Real',
  },
  {
    id: 83,
    title: 'Archaeological Excavation Uncovers Ancient Civilization Artifacts',
    excerpt: 'Historical dig reveals priceless artifacts from ancient Nepal kingdoms.',
    content: '<p>Archaeological excavations in Nepal uncovered significant artifacts from ancient civilizations providing insights into historical kingdoms. The discoveries contribute to understanding of South Asian ancient history.</p>',
    category: 'Science',
    author: 'Dr. Ashok Singh',
    publishedAt: '1 day ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3845698/pexels-photo-3845698.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '18.9k',
    comments: 127,
    tags: ['archaeology', 'history', 'science'],
    modelResult: 'Real',
  },
  {
    id: 84,
    title: 'Renewable Energy Research Initiative Launched',
    excerpt: 'Scientific institutions pursue solar and wind energy development programs.',
    content: '<p>Nepali scientific institutions launched comprehensive renewable energy research initiative focusing on solar and wind applications. The research aims to develop sustainable energy solutions for Nepal.</p>',
    category: 'Science',
    author: 'Prof. Suresh Bhatt',
    publishedAt: '2 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3531670/pexels-photo-3531670.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '15.3k',
    comments: 89,
    tags: ['science', 'renewable energy', 'research'],
    modelResult: 'Real',
  },
  {
    id: 85,
    title: 'Marine Biology Research Station Established',
    excerpt: 'Research facility opens to study aquatic ecosystems and conservation.',
    content: '<p>Nepal established its first marine biology research station to study aquatic ecosystems and marine species conservation. The facility supports scientific understanding of water resources and biodiversity.</p>',
    category: 'Science',
    author: 'Dr. Neela Kumari',
    publishedAt: '2 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/1080120/pexels-photo-1080120.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '12.6k',
    comments: 71,
    tags: ['marine biology', 'conservation', 'research'],
    modelResult: 'Suspicious',
  },
  {
    id: 86,
    title: 'Genetic Research Program Identifies Disease Markers',
    excerpt: 'Scientists identify genetic markers for hereditary disease prevention.',
    content: '<p>Nepali genetic researchers identified disease markers helpful in early disease detection and prevention. The research contributes to personalized medicine and preventive healthcare approaches.</p>',
    category: 'Science',
    author: 'Dr. Anita Lohani',
    publishedAt: '2 days ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3831645/pexels-photo-3831645.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '16.2k',
    comments: 103,
    tags: ['genetics', 'medicine', 'research'],
    modelResult: 'Real',
  },
  {
    id: 87,
    title: 'Seismic Monitoring Network Expanded',
    excerpt: 'Earthquake detection system upgrades improve disaster early warning capability.',
    content: '<p>Nepal expanded its seismic monitoring network with new detection stations improving earthquake early warning capabilities. The enhanced system provides better disaster preparedness for earthquake-prone regions.</p>',
    category: 'Science',
    author: 'Dr. Govind Sharma',
    publishedAt: '2 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3827495/pexels-photo-3827495.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '14.8k',
    comments: 81,
    tags: ['seismic', 'disaster', 'science'],
    modelResult: 'Real',
  },
  {
    id: 88,
    title: 'Pollution Control Research Develops Air Quality Solutions',
    excerpt: 'Scientists develop technology to reduce air pollution in urban areas.',
    content: '<p>Nepali scientists developed innovative technology to reduce air pollution in urban environments. The air purification system shows promise in combating increasing air quality problems in cities.</p>',
    category: 'Science',
    author: 'Prof. Ramesh Poudel',
    publishedAt: '2 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3616356/pexels-photo-3616356.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '17.5k',
    comments: 94,
    tags: ['pollution', 'environment', 'technology'],
    modelResult: 'Real',
  },
  {
    id: 89,
    title: 'Psychology Research on Mental Resilience Published',
    excerpt: 'Nepali researchers study stress management and psychological resilience factors.',
    content: '<p>Nepali psychology researchers published extensive study on psychological resilience and stress management. The research provides insights into mental health support and wellbeing promotion strategies.</p>',
    category: 'Science',
    author: 'Dr. Sunita Niraula',
    publishedAt: '3 days ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3808714/pexels-photo-3808714.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '13.2k',
    comments: 78,
    tags: ['psychology', 'mental health', 'research'],
    modelResult: 'Real',
  },
  {
    id: 90,
    title: 'Astrophysics Observation Station Opens for Research',
    excerpt: 'High-altitude observatory facility enables celestial research and astronomy studies.',
    content: '<p>Nepal opened a new high-altitude astrophysics observation station enabling advanced celestial research. The facility supports Nepal\'s participation in international astronomy research collaborations.</p>',
    category: 'Science',
    author: 'Prof. Bikram Sharma',
    publishedAt: '3 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3246650/pexels-photo-3246650.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '11.7k',
    comments: 67,
    tags: ['astronomy', 'research', 'space'],
    modelResult: 'Real',
  },
  {
    id: 91,
    title: 'Nanotechnology Research Develops Medical Applications',
    excerpt: 'Scientists apply nanotechnology to develop advanced medical diagnostic tools.',
    content: '<p>Nepali nanotechnology researchers developed innovative medical diagnostic tools using nanotechnology. The applications include advanced disease detection and personalized treatment approaches.</p>',
    category: 'Science',
    author: 'Dr. Saurav Paudel',
    publishedAt: '3 days ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3936316/pexels-photo-3936316.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '14.9k',
    comments: 89,
    tags: ['nanotechnology', 'medicine', 'research'],
    modelResult: 'Fake',
  },
  // Health (12 articles)
  {
    id: 92,
    title: 'Yoga and Ayurveda Gaining Global Popularity from Nepal',
    excerpt: 'Ancient wellness practices from Nepal attract international practitioners and students.',
    content: '<p>Nepal\'s traditional yoga and Ayurveda practices gained tremendous international popularity with students worldwide. The wellness disciplines contribute to Nepal\'s health tourism and cultural reputation.</p>',
    category: 'Health',
    author: 'Dr. Michael Scott',
    publishedAt: '2 days ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3807517/pexels-photo-3807517.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '17.9k',
    comments: 84,
    tags: ['health', 'yoga', 'ayurveda'],
    modelResult: 'Suspicious',
  },
  {
    id: 93,
    title: 'Mental Health National Campaign Launches Awareness',
    excerpt: 'Government initiated mental health awareness campaign addressing stigma and support.',
    content: '<p>Nepal government launched comprehensive mental health awareness campaign addressing psychological wellbeing and support resources. The campaign aims to reduce stigma and encourage seeking professional help.</p>',
    category: 'Health',
    author: 'Dr. Jennifer Aniston',
    publishedAt: '2 days ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/3808714/pexels-photo-3808714.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '21.3k',
    comments: 156,
    tags: ['health', 'mental health', 'awareness'],
    modelResult: 'Real',
  },
  {
    id: 94,
    title: 'Organic Agriculture Expansion Improves Food Security',
    excerpt: 'Farmers adopt organic cultivation methods enhancing food security and environmental health.',
    content: '<p>Nepal\'s organic agriculture sector expanded significantly with increased farmer participation. Organic farming methods improve soil health, reduce chemical pollution, and enhance nutritional food value.</p>',
    category: 'Health',
    author: 'Dr. Robert Newman',
    publishedAt: '2 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '19.6k',
    comments: 123,
    tags: ['health', 'food security', 'agriculture'],
    modelResult: 'Real',
  },
  {
    id: 95,
    title: 'Primary Health Centers Expansion Reaches Remote Villages',
    excerpt: 'Healthcare infrastructure expands providing basic medical services to remote communities.',
    content: '<p>Nepal expanded primary healthcare centers network reaching remote mountain villages. The infrastructure expansion ensures basic medical services and health awareness reach underserved populations.</p>',
    category: 'Health',
    author: 'Dr. Susan Harris',
    publishedAt: '2 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/4720303/pexels-photo-4720303.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '15.7k',
    comments: 92,
    tags: ['health', 'healthcare', 'rural'],
    modelResult: 'Real',
  },
  {
    id: 96,
    title: 'Nutrition Education Program for Mothers and Children',
    excerpt: 'Government initiative improves maternal and child nutrition outcomes.',
    content: '<p>Nepal implemented comprehensive nutrition education program targeting mothers and children. The program provides nutritional guidance and supplementation improving child growth and maternal health outcomes.</p>',
    category: 'Health',
    author: 'Dr. Kalpana Sharma',
    publishedAt: '3 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/4720307/pexels-photo-4720307.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '13.2k',
    comments: 78,
    tags: ['health', 'nutrition', 'children'],
    modelResult: 'Real',
  },
  {
    id: 97,
    title: 'Chronic Disease Prevention Programs Show Success',
    excerpt: 'Health initiatives effectively reduce diabetes and hypertension prevalence.',
    content: '<p>Nepal\'s chronic disease prevention programs showed measurable success reducing diabetes and hypertension prevalence. Health interventions focus on lifestyle modifications and early disease detection.</p>',
    category: 'Health',
    author: 'Dr. Bijaya Kumar',
    publishedAt: '3 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/4720315/pexels-photo-4720315.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '12.8k',
    comments: 71,
    tags: ['health', 'disease prevention', 'wellness'],
    modelResult: 'Real',
  },
  {
    id: 98,
    title: 'Herbal Medicine Research Validates Traditional Treatments',
    excerpt: 'Scientific studies confirm effectiveness of Nepali traditional herbal medicines.',
    content: '<p>Scientific research validated effectiveness of traditional Nepali herbal medicines for various health conditions. The studies preserve indigenous knowledge while establishing scientific credibility of traditional treatments.</p>',
    category: 'Health',
    author: 'Prof. Prakash Thakuri',
    publishedAt: '3 days ago',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/1537919/pexels-photo-1537919.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '18.4k',
    comments: 94,
    tags: ['health', 'herbal medicine', 'traditional'],
    modelResult: 'Real',
  },
  {
    id: 99,
    title: 'Water Quality Improvement Reduces Waterborne Diseases',
    excerpt: 'Infrastructure improvements enhance drinking water quality and public health.',
    content: '<p>Nepal invested in water quality improvement infrastructure reducing waterborne disease incidence significantly. Safe drinking water access improves public health and reduces medical burdens on healthcare system.</p>',
    category: 'Health',
    author: 'Dr. Ravi Poudel',
    publishedAt: '3 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3807519/pexels-photo-3807519.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '16.1k',
    comments: 87,
    tags: ['health', 'water quality', 'sanitation'],
    modelResult: 'Suspicious',
  },
  {
    id: 100,
    title: 'Sports Medicine Clinic Opens for Athletic Injury Treatment',
    excerpt: 'Specialized medical facility treats sports-related injuries and enhances athletic performance.',
    content: '<p>Nepal opened its first dedicated sports medicine clinic providing specialized treatment for athletic injuries. The facility supports athlete health, performance optimization, and injury rehabilitation services.</p>',
    category: 'Health',
    author: 'Dr. Hari Prasad',
    publishedAt: '3 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/4720311/pexels-photo-4720311.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '11.5k',
    comments: 63,
    tags: ['health', 'sports medicine', 'athlete'],
    modelResult: 'Real',
  },
  {
    id: 101,
    title: 'Public Health Surveillance System Modernized',
    excerpt: 'Digital health monitoring improves disease tracking and outbreak response.',
    content: '<p>Nepal modernized its public health surveillance system with digital disease monitoring capabilities. The enhanced system enables rapid disease detection and coordinated outbreak response.</p>',
    category: 'Health',
    author: 'Dr. Sujata Karki',
    publishedAt: '3 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/3938055/pexels-photo-3938055.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '13.9k',
    comments: 76,
    tags: ['health', 'surveillance', 'disease'],
    modelResult: 'Real',
  },
  {
    id: 102,
    title: 'Sleep Medicine Research Addresses Sleep Disorder Epidemic',
    excerpt: 'Study reveals sleep disorder prevalence and develops treatment protocols.',
    content: '<p>Nepali sleep medicine researchers conducted comprehensive study on sleep disorders revealing prevalence and health impacts. Research develops treatment protocols addressing growing sleep-related health issues.</p>',
    category: 'Health',
    author: 'Dr. Deepa Adhikari',
    publishedAt: '3 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/4720318/pexels-photo-4720318.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '12.3k',
    comments: 68,
    tags: ['health', 'sleep', 'research'],
    modelResult: 'Real',
  },
  {
    id: 103,
    title: 'Health Insurance Program Expands Coverage',
    excerpt: 'Universal health insurance initiative increases access to medical services.',
    content: '<p>Nepal expanded health insurance program significantly increasing coverage for medical services. The initiative improves financial protection for patients and healthcare access equity.</p>',
    category: 'Health',
    author: 'Dr. Nirmal Singh',
    publishedAt: '3 days ago',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/4720320/pexels-photo-4720320.jpeg?auto=compress&cs=tinysrgb&w=600',
    views: '14.6k',
    comments: 81,
    tags: ['health', 'insurance', 'access'],
    modelResult: 'Real',
  },
];

export const getArticleById = (id: number): NewsArticle | undefined => {
  return newsArticles.find(article => article.id === id);
};

export const getArticlesByCategory = (category: string): NewsArticle[] => {
  if (category === 'All') return newsArticles;
  return newsArticles.filter(article => article.category === category);
};

export const getFeaturedArticles = (): NewsArticle[] => {
  return newsArticles.filter(article => article.featured);
};

export const getTrendingArticles = (): NewsArticle[] => {
  return newsArticles.filter(article => article.trending);
};
